{% set name = "tad-dftd3" %}
{% set version = "0.5.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tad_dftd3-{{ version }}.tar.gz
  sha256: 8fb8af1e5ad84a4221c07924db9d96e2343c719139390867ca44e43450dc8cfb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy <2
    - pytorch >=1.11,<3
    - tad-mctc ==0.5.3
    - typing-extensions

test:
  imports:
    - tad_dftd3
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Torch autodiff DFT-D3 implementation
  home: https://github.com/dftd3/tad-dftd3
  dev_url: https://github.com/dftd3/tad-dftd3
  doc_url: https://tad-dftd3.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
