{% set name = "tad-dftd3" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tad_dftd3-{{ version }}.tar.gz
  sha256: e1cfeaecf7145594a2ce8a52c650f17a61e69759fdb83c7719af025ebc83ee69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools
    - pip
  run:
    - python >=3.8,<3.13
    - numpy <2
    - tad-mctc
    - pytorch >=1.11,<2.5

test:
  imports:
    - tad_dftd3
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Torch autodiff DFT-D3 implementation
  home: https://github.com/dftd3/tad-dftd3
  dev_url: https://github.com/dftd3/tad-dftd3
  doc_url: https://tad-dftd3.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
