{% set name = "tad-dftd3" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tad_dftd3-{{ version }}.tar.gz
  sha256: 5f3e5741a679c0f8253b165029afafce64aac3eba27fd3148576adc82931eb1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy
    - tad-mctc
    - pytorch

test:
  imports:
    - tad_dftd3
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Torch autodiff DFT-D3 implementation
  home: https://github.com/dftd3/tad-dftd3
  dev_url: https://github.com/dftd3/tad-dftd3
  doc_url: https://tad-dftd3.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
